### ISSUE TITLE
Feature request: option to indicate changed words

### ISSUE THREAD

**Issue by jambosmitty** [dan-lovelace/word-replacer-max#23]
It would be good to have the option to subtly indicate when a word has been swapped out. Maybe an option to underline or italicise or recolour etc? This would help to avoid confusion when a word replaces in a way that wasn't expected and you spend a few seconds being extremely confused by what you're reading.

**Comment by dan-lovelace** [comment]
Hey @jambosmitty - This is a great idea. There are a couple things I'm considering initially:

1. Should this be available on a per-rule basis, globally (all rules), or both? Are there cases where a replacement should not be highlighted if the global option is enabled?
2. How much customization is desired? The extension could surface some defaults (as you mentioned: underline, italicize, etc.) and could go as far as offering a custom CSS stylesheet. Would the stylesheet be overkill?

I'm open to feedback if you have any, otherwise I'll start coming up with a plan for this and work on getting an update in the store soon. This one may require a bit of extra time planning UI/UX. Thanks for your patience in the meantime.

**Comment by jambosmitty** [comment]
Hi @dan-lovelace 
1.  An option for both I think is ideal. I personally have 2 use cases for the extension which are quite different, so an option to only highlight some would be great. Maybe as you were saying have the per-rule setting just inverse what the global setting is?
2. For me custom CSS is overkill, I think a good set of default options is all that's needed, but that's just me

No worries for any wait at all I'm having a great time over here replacing every instance of "Elon Musk" with "Twat" - makes reading the news way more enjoyable

**Comment by dan-lovelace** [comment]
Great stuff @jambosmitty, thanks for providing more details. Glad to hear you're enjoying the extension!

**Comment by dan-lovelace** [comment]
Hey @jambosmitty thanks for hanging in there on this one. Work for this has been complete and new versions submitted to both the Chrome and Firefox stores. It may take a day or two for it to be available in Chrome. In the meantime, the new interface may be viewed in this pull request: https://github.com/dan-lovelace/word-replacer-max/pull/24.

I hope this resolves your issue but don't hesitate to reach back out if there's anything more you need.
