### ISSUE TITLE
[Feature request] Filter links by words

### ISSUE THREAD

**Issue by hetszunyukapanyanyimonyok** [dan-lovelace/word-replacer-max#32]
Hello!

Thank you for this project and your time!
Would it be possible to add this function:

If a link title contains specific few words the extension hides the link completely.

On any site!

For example: 
I am searching for imdb best horror movies 50 lists.
And I want to hide specific movies that I already watched.

movie title:
Bloody chipmunks eat my cornflakes 
link(fake):
""imdb.com/movie/73626627""

And the "filter:chipmunks eat" words that are in that link title it would hide the link completely with the title of course.... .

Thank you again. I would help to program it but I have no idea.

**Comment by dan-lovelace** [comment]
Hello @hetszunyukapanyanyimonyok -

Thanks for your interest! While Word Replacer Max is great for text replacement, for completely hiding links based on their content, I'd actually recommend using [Tampermonkey](https://www.tampermonkey.net/) instead. Tampermonkey is a userscript manager that would let you write a simple script to:

1. Find links containing specific text (like your watched movie titles)
2. Completely hide those links from the page (this could even be configured for IMDB specifically to remove the entire result from the list instead of just its link)
3. Work across any website
4. Handle partial matches exactly as you described

While it does require a tiny bit of JavaScript knowledge, there are lots of examples and templates around that make it quite approachable even for beginners.

Does this sound like something you'd be comfortable exploring yourself?

**Comment by hetszunyukapanyanyimonyok** [comment]
Of course, thank your for your help. I will check it out!
