### ISSUE TITLE
Creating many rules exceeds the storage limit

### ISSUE THREAD

**Issue by martingregoire** [dan-lovelace/word-replacer-max#4]
Hi @dan-lovelace, thanks for creating this extension!

While trying to create a big list of rules, I noticed that there seems to be a limit on the amount/size of rules.

### Issue

This shows when:
- trying to import more rules: the toast says "3 rules imported successfully.", but no rules were actually imported
- trying to create more rules: clicking the "New rule" button does nothing

To my understanding this is related to the limit on the storage, see https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/sync. Accd. to this each item may have a size of 8192 bytes.

Working with the Chrome console for the extension, while trying to do one of the actions mentioned above, I see this:

> popup-DFDUfXxr.js:37 Uncaught (in promise) 
> Error: QUOTA_BYTES_PER_ITEM quota exceeded

This is the current size of the stored rules:

```js
chrome.storage.sync.get('matchers', (data) => console.log(JSON.stringify(data).length))
// 8122
```

Would it be possible to store the rules in a different way? The total amount of sync storage is 100kB, which should be sufficient.

### Context

I'm trying to replace text on a page that renders hours and minutes. It renders these as something like `5,166667`, which I would like to instead show as `5h10m`.

For this I basically need 59 rules (as "5 hours" is rendered as `5`, which needs no replacements).

### Reproduction

Please find attached two rules files that demonstrate the issue.

Importing `rules_1.json` works fine. After that, you cannot create or import more rules.

[rules_1.json](https://github.com/user-attachments/files/16233322/rules_1.json)
[rules_2.json](https://github.com/user-attachments/files/16233324/rules_2.json)

**Comment by dan-lovelace** [comment]
Thanks for the detailed report @martingregoire. You're right, the storage type I've chosen has a pretty low size limit. I weighed the different options during initial development and chose `sync` since there's less friction keeping things synced between machines for the average user.

I can add support for `local` which should better handle your case: https://developer.chrome.com/docs/extensions/reference/api/storage#property-local. Before I do this, please allow me some time to think about the best way to present the new option in the UI and handle switching between the two.

One question, perhaps for you, is how should the system handle changing from `local` to `sync`? With the smaller available storage bank, the user will need to be warned before loss of their current data and potentially be offered the ability to back things up first. I'm open to any suggestions here but my first thought is a little confirmation dialog with "I understand, continue" and "Cancel" buttons.

I'll get to work on the initial feature buildout and report back here when done.

**Comment by martingregoire** [comment]
Thanks for taking a look at this! I think the `local` storage would work perfectly fine for my use case.

The confirmation dialog sounds fine to me. A bonus could be to first check if the `local` matchers would fit into the `sync` matchers (maybe using `browser.storage.sync.getBytesInUse('matchers')` and compare to `JSON.stringify()..length`?), and if so, do not show this dialog.

Or maybe a different approach would also work, where all the data is kept in the `sync` storage, but stored differently?
I was thinking about moving the matchers to the top level, something like this:

```json
{
  "domainList": [...],
  "matchers": [
    "some-uuid",
    "some-other-uuid",
    ...
  ],
  "preferences": {...},
  "matcher-some-uuid": { "active": true, "queries": [...], "queryPatterns": [...], "replacement": "..." },
  "matcher-some-other-uuid": { "active": false, "queries": [...], "queryPatterns": [...], "replacement": "..." },
  ...
}
```

This way every single matcher can store up to 8kB, and hundreds of matchers can be stored (item count limit is 512).

It could even be "normalized" a bit more to optimize reading the active matchers:

```json
{
  "domainList": [...],
  "activeMatchers": [
    "some-uuid",
    ...
  ],
  "inactiveMatchers": [
    "some-other-uuid",
    ...
  ],
  "preferences": {...},
  "matcher-some-uuid": { "queries": [...], "queryPatterns": [...], "replacement": "..." },
  "matcher-some-other-uuid": { "queries": [...], "queryPatterns": [...], "replacement": "..." },
  ...
}
```

What do you think, would this make sense?

**Comment by dan-lovelace** [comment]
Oh sure, I see what you mean by storing them as a flat structure with `sync` instead. Let me look into that since it would be a better cross-device experience. It would be nice if the API allowed wildcard queries but that does not seem to be supported at the moment.

I'll move forward with this approach for now and include an automatic migration function to move old settings to the new shape if they exist. That should allow seamless integration with the new changes.

Thanks for your input and help getting this resolved!

**Comment by dan-lovelace** [comment]
@martingregoire thanks for your patience while I work this out. I've finalized an initial BETA version in case you're interested in trying it out before it hits the extension stores. Be sure to backup your data first if you do. I'll be doing lots of testing between today and tomorrow with the goal of having a new version published before the weekend.

BETA packages:

Manifest v2: [word-replacer-max_0.3.0-beta.0_m2.zip](https://github.com/user-attachments/files/16285046/word-replacer-max_0.3.0-beta.0_m2.zip)
Manifest v3: [word-replacer-max_0.3.0-beta.0_m3.zip](https://github.com/user-attachments/files/16285044/word-replacer-max_0.3.0-beta.0_m3.zip)

**Comment by martingregoire** [comment]
Hi @dan-lovelace, thanks for your quick reply and fix! I downloaded the v3 version and can confirm that it fixes the issue. 👍 
I can now import both rules files, and still create new rules afterwards.

I'm not sure if the "migration" part is already included, or if it did not work because of the way I installed this beta package?
Here's what I did:
- remove all versions of the extension
- install extension 0.2.0 via Chrome Web Store
- import the `rules_1.json` file
- install extension 0.3.0 via `chrome://extensions/` ("Developer mode" enabled, button "Load unpacked")
  - note: I had to edit the `manifest.json` file and change the `"version"` field to `"0.3.0.0"`, as Chrome allows only digits there

Now that both extension versions are installed at the same time, the 0.3.0 version does not show the imported rules, but only the "I was surprised" default rule.

**Comment by dan-lovelace** [comment]
Thanks for taking a run through the new version @martingregoire, I'm glad the refactor resolves your issue. Testing the upgrade path is a little tedious since browsers partition extension storage by ID. When you have both versions installed, they have different identifiers so the storage is not shared. I've left steps for testing this below for future reference.

My own testing of the migration has gone really well and I've written some tests around it too. I feel confident enough that I can stick to my original estimate of having this submitted before the weekend. As long as testing continues to go well, I'm going to finalize a new version tonight and have the upgraded packages submitted to stores around 9PM Eastern.

---

Upgrade test in Chrome:

1. Install both extensions as you already have
2. Inspect the service worker of v0.2.0 - It sounds like you already know how to do this but it's found on the extension settings page if not
3. Run `await chrome.storage.sync.get();` in the console - It should print an object with keys `domainList`, `matchers` and `preferences`
4. Right click the entire object result row (tip: don't expand it) and choose "Copy object" to put the whole thing in your clipboard
5. Paste the object to a new file because you'll need it later - This also ensures you have a fresh backup somewhere
6. Inspect the service worker for v0.3.0
8. Run `await chrome.storage.sync.clear();`
9. Run `await chrome.storage.sync.set(<MY_SETTINGS>);` - Replace `<MY_SETTINGS>` with your copied settings from v0.2.0 - There's a storage change listener so the migration should happen automatically at this point 
11. Open the v0.3.0 popup window in your toolbar
12. The rules from v0.2.0 are rendered successfully

**Comment by martingregoire** [comment]
Thanks for the detailed description of the migration testing! I can confirm that it worked just fine for me.

**Comment by dan-lovelace** [comment]
Alright @martingregoire the fixes for this issue have been submitted to both Chrome and Firefox stores. I sincerely appreciate your assistance with everything, it's quite rare to find someone so open to providing feedback and help.

If there's anything else you need, don't hesitate to reach back out!
